use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AgentConfig {
    #[serde(default = "default_database_path")]
    pub database_path: PathBuf,

    #[serde(default = "default_listen_address")]
    pub listen_address: String,

    #[serde(default = "default_polling_enabled")]
    pub polling_enabled: bool,

    #[serde(default = "default_polling_interval")]
    pub polling_interval_seconds: u64,

    #[serde(default = "default_log_level")]
    pub log_level: String,

    #[serde(default = "default_provider_timeout")]
    pub provider_timeout_seconds: u64,

    #[serde(default = "default_retention_days")]
    pub retention_days: u32,

    #[serde(default = "default_auto_start")]
    pub auto_start: bool,
}

fn default_database_path() -> PathBuf {
    directories::BaseDirs::new()
        .map(|base| {
            base.data_local_dir()
                .join("ai-consumption-tracker")
                .join("usage.db")
        })
        .unwrap_or_else(|| PathBuf::from(".ai-consumption-tracker/usage.db"))
}

fn default_listen_address() -> String {
    "127.0.0.1:8080".to_string()
}

fn default_polling_enabled() -> bool {
    true
}

fn default_polling_interval() -> u64 {
    300
}

fn default_log_level() -> String {
    "info".to_string()
}

fn default_provider_timeout() -> u64 {
    30
}

fn default_retention_days() -> u32 {
    30
}

fn default_auto_start() -> bool {
    false
}

impl Default for AgentConfig {
    fn default() -> Self {
        Self {
            database_path: default_database_path(),
            listen_address: default_listen_address(),
            polling_enabled: default_polling_enabled(),
            polling_interval_seconds: default_polling_interval(),
            log_level: default_log_level(),
            provider_timeout_seconds: default_provider_timeout(),
            retention_days: default_retention_days(),
            auto_start: default_auto_start(),
        }
    }
}

impl AgentConfig {
    pub fn load() -> Result<Self, Box<dyn std::error::Error>> {
        let config_path = Self::config_path();

        if config_path.exists() {
            let content = std::fs::read_to_string(&config_path)?;
            toml::from_str(&content).map_err(|e| e.into())
        } else {
            let config = Self::default();
            config.save()?;
            Ok(config)
        }
    }

    pub fn save(&self) -> Result<(), Box<dyn std::error::Error>> {
        let config_path = Self::config_path();

        if let Some(parent) = config_path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        let content = toml::to_string_pretty(self)?;
        std::fs::write(&config_path, content)?;

        Ok(())
    }

    fn config_path() -> PathBuf {
        directories::BaseDirs::new()
            .map(|base| {
                base.config_dir()
                    .join("ai-consumption-tracker")
                    .join("agent.toml")
            })
            .unwrap_or_else(|| PathBuf::from("agent.toml"))
    }

    pub fn sample_config() -> &'static str {
        r#"# AI Consumption Tracker Agent Configuration
# Generated by aic-agent config --generate

[agent]
# Database file path (SQLite)
database_path = "~/.local/share/ai-consumption-tracker/usage.db"

# HTTP API listen address
listen_address = "127.0.0.1:8080"

# Enable background polling
polling_enabled = true

# Polling interval in seconds (default: 300 = 5 minutes)
polling_interval_seconds = 300

# Log level: debug, info, warn, error
log_level = "info"

# Provider request timeout in seconds
provider_timeout_seconds = 30

# Data retention period in days
retention_days = 30

# Auto-start agent on system boot (requires service setup)
auto_start = false

# Example: Exclude specific providers from polling
# excluded_providers = ["provider_id_1", "provider_id_2"]

# Example: Turso remote database configuration (optional)
# [database.turso]
# url = "libsql://your-db.turso.io"
# auth_token = "your-auth-token"
"#
    }

    pub fn generate_config_file(
        path: Option<PathBuf>,
    ) -> Result<PathBuf, Box<dyn std::error::Error>> {
        let config_path = path.unwrap_or_else(Self::config_path);

        if let Some(parent) = config_path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        std::fs::write(&config_path, Self::sample_config())?;

        Ok(config_path)
    }
}
